### ISSUE TITLE
How to get an initial value from an iterator

### ISSUE THREAD

**Issue by aaronshaf** [staltz/callbag-merge#1]
```
    pipe(
      merge(fromIter(["focus"]), fromEvent(window, "blur"), fromEvent(window, "focus")),
      forEach(event => {
        console.log(event);
      })
    );
```

I am trying to have an initial value of "focus" before any blur/focus events are fired. Any ideas?

**Comment by staltz** [comment]
I'd recommend not using merge with pullables. Try callbag-sample. It samples a pullable every time a listenable emits an event
